name: tagrupos
description: Desarrollo de Ingeniería. Clínica de Tecnología Asistiva, Fleni
publish_to: "none"
version: 1.0.1+4

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_riverpod: ^2.4.10
  flutter_tts: ^4.0.2
  get_it: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.1.0
  url_launcher: ^6.2.4
  stroke_text: ^0.0.3

dev_dependencies:
  build_runner: ^2.4.8
  change_app_package_name: ^1.2.0
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
flutter_native_splash:
  color: "#003A70"
  image: "assets/images/tagrupos-iso.png"
