name: tagrupo
description: Desarrollo de Ingeniería. Clínica de Tecnología Asistiva, FLENI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_tts: ^3.6.3
  font_awesome_flutter: ^10.6.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
flutter_native_splash:
  color: "#003A70"
  image: "assets/images/tagrupo-iso.png"
